# Generated by Django 5.0.6 on 2024-06-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='default value', max_length=100),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
