# Generated by Django 5.0.6 on 2024-06-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_category_description_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='default value', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
