# Generated by Django 5.0.6 on 2024-06-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='woocomerceuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(default='default value', max_length=1000)),
                ('secret_key', models.CharField(default='default value', max_length=1000)),
            ],
        ),
    ]
