# Generated by Django 5.0.6 on 2024-06-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_woocomerceuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='integrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='default value', max_length=255)),
                ('consumer_key', models.CharField(default='default value', max_length=1000)),
                ('secret_key', models.CharField(default='default value', max_length=1000)),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(default='Integration Name', max_length=255)),
                ('description', models.CharField(default='default value', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='woocomerceuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
